const express = require('express')
const mongoose = require('mongoose')
const helmet = require('helmet')
const { errors } = require('celebrate')
const handlerError = require('./middlewares/handlerError')
const routerUsers = require('./routes/users')
const routerCards = require('./routes/cards')
const NotFoundError = require('./errors/NotFoundError')
const { PORT, DB_ADDRESS } = require('./config')
const { requestLogger, errorLogger } = require('./middlewares/logger')

mongoose.connect(DB_ADDRESS)

const app = express()
app.use(express.json())
app.use(helmet())
app.use(requestLogger)
app.use('/', routerUsers)
app.use('/users', routerUsers)
app.use(routerCards)
app.use((req, res, next) => {
  next(new NotFoundError('Запрашиваемая страница не найдена'))
})
app.use(errorLogger)
app.use(errors())
app.use(handlerError)

app.listen(PORT, () => {
  console.log(`Sever is running on port ${PORT}`)
})
